### ISSUE TITLE
[Objetivo-2] [M1-2] Modelo de datos para las plantillas

### ISSUE THREAD

**Issue by delightfulagony** [jmramirezG/WhatCook#10]
# Problema
Hace falta un modelo de datos para las plantillas de documentos a fin de generar los documentos como se describe en [HU2] #3. Además servirá como punto de partida para trabajar con los documentos para [HU1] #2 [HU3] #4 y [HU4] #5
Abro este ticket para investigar y discutir acerca de ello.

**Comment by delightfulagony** [comment]
He estado mirando acerca del tema y diría que hay un par de opciones, [me ha parecido entender que MS Word ofrece un sistema de plantillas XML, que creo sería editable por código](https://learn.microsoft.com/en-us/power-platform/admin/using-word-templates-dynamics-365) y la otra opción, por la cual yo me decantaría es usar un lenguaje de marcado directamente para generar los documentos, preferiblemente LaTeX o Markdown dependiendo del grado de personalización que se quiera de los documentos. 
***
He encontrado unos cuantos recursos para ello, la mayoría usan Python y LaTeX pero realmente creo que da un poco igual:
 - [Using LaTeX for fast document generation](https://www.lesinskis.com/LaTeX_for_fast_document_generation.html)
 - [Automated Document Creation and Typesetting with LaTeX](https://mpetroff.net/2015/06/automated-document-creation-and-typesetting-with-latex/)
 - [The Ultimate Guide to Document Automation in 2022](https://research.aimultiple.com/document-automation/)
 - [Automated Document Generation with Python & LaTeX](https://www.linkedin.com/pulse/automated-document-generation-python-latex-sajil-c-k/?articleId=6511111955351212032)
***
He visto también un par de librerías de Go que implementan algún tipo de generación de documento de LaTeX, aunque no sé si servirían para nuestro caso de uso.
 - https://github.com/go-latex/latex
 - https://github.com/apourchet/go-latex

**Comment by jmramirezG** [comment]
Hola!

Lo suyo sería guardar las templates en docx, ya que la mayoría de aplicaciones/librerías que generan pdfs a partir de una plantilla usan este formato.

He encontrado esto, [pdftron](https://www.pdftron.com/documentation/go), una librería para go que permite generar, dado un docx y un json, un pdf.

Esto sería ideal, ya que podemos directamente desde lo que nos venga del frontend (que sería un json, probablemente) sin hacer ninguna transformación usarlo para la plantilla, simplificando nuestro trabajo en el futuro.

Comentame qué te parece.

Estoy disponible!

**Comment by delightfulagony** [comment]
Pues no había visto eso de pdftron, la verdad es que nos viene como anillo al dedo.

He hecho una propuesta de modelo usando pdftron en 5869c18, échale un ojo a ver qué te parece! ^^

**Comment by delightfulagony** [comment]
Este ticket discute detalles de implementación relevantes a [HU2] https://github.com/jmramirezG/WhatCook/issues/3
