### ISSUE TITLE
[Objetivo-2] [M1] Hace falta un modelo de datos para los clientes

### ISSUE THREAD

**Issue by delightfulagony** [jmramirezG/WhatCook#8]
# Problema
Es necesario un modelo de datos para los clientes a fin de generar los documentos como se describe en [HU2] #3 

# Decisiones técnicas
¿Qué datos debe almacenar este modelo para ser útil para resolver nuestro problema?

***

> ### Se ha reescrito el cuerpo del issue para trabajar en el dominio del problema
> Dado que es necesario almacenar nombre completo y correo electrónico propongo el siguiente modelo
>
```
Cliente {
    nombre: []string
    apellidos: []string
    correo: []string
}
```
>
> Supongo que debería ser una entidad ya que los usuarios deberán poder hacer cosas, aunque sea cambiar su correo electrónico.
>
> He estado buscando un poco sobre como guardar emails en BBDD y no he encontrado gran cosa, aunque hay un par de artículos interesantes ninguno habla explícitamente del tema, aunque los paso igualmente por si te son de interés
> > - https://dba.stackexchange.com/questions/37014/in-what-data-type-should-i-store-an-email-address-in-database
> > - https://stackoverflow.com/questions/549/the-definitive-guide-to-form-based-website-authentication/477578#477578

**Comment by jmramirezG** [comment]
Nombre y apellidos me parecen guay como string.

El correo lo veo bien como string también, se podría implementar en el frontend (o backend) una validación de que el correo introducido es válido, como sería una expresión regular que valide lo que se especifica en [la respuesta](https://dba.stackexchange.com/a/37021) de uno de los links que has mandado.

Comentame que te parece!

**Comment by jmramirezG** [comment]
He asignado esta issue al M1 para que se pueda visualizar qué estamos solucionando!

**Comment by delightfulagony** [comment]
> El correo lo veo bien como string también, se podría implementar en el frontend (o backend) una validación de que el correo introducido es válido, como sería una expresión regular que valide lo que se especifica en [la respuesta](https://dba.stackexchange.com/a/37021) de uno de los links que has mandado.

Creo que la validación de emails es un arte en sí mismo :laughing: podría ser perfectamente su propio milestone si quiere hacerse bien.

**Comment by jmramirezG** [comment]
> Creo que la validación de emails es un arte en sí mismo laughing podría ser perfectamente su propio milestone si quiere hacerse bien.

Totalmente de acuerdo con esto.

Buscando un poco he encontrado este chorizo:

```([-!#-'*+/-9=?A-Z^-~]+(\.[-!#-'*+/-9=?A-Z^-~]+)*|"([]!#-[^-~ \t]|(\\[\t -~]))+")@([0-9A-Za-z]([0-9A-Za-z-]{0,61}[0-9A-Za-z])?(\.[0-9A-Za-z]([0-9A-Za-z-]{0,61}[0-9A-Za-z])?)*|\[((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){3}|IPv6:((((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){6}|::((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){5}|[0-9A-Fa-f]{0,4}::((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){4}|(((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):)?(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}))?::((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){3}|(((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){0,2}(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}))?::((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){2}|(((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){0,3}(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}))?::(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):|(((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){0,4}(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}))?::)((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3})|(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){3})|(((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){0,5}(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}))?::(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3})|(((0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}):){0,6}(0|[1-9A-Fa-f][0-9A-Fa-f]{0,3}))?::)|(?!IPv6:)[0-9A-Za-z-]*[0-9A-Za-z]:[!-Z^-~]+)])```

[Adjunto enlace](https://www.abstractapi.com/guides/email-address-pattern-validation) de donde viene explicado, porque sinceramente me supera, pero tiene buena pinta.

**Comment by JJ** [comment]
No se menciona ninguna historia de usuario en este issue. Es imposible, por tanto, saber qué es correcto y qué no lo es.

**Comment by delightfulagony** [comment]
Este ticket discute detalles de implementación relevantes a [HU2] #3

**Comment by JJ** [comment]
Un modelo *del problema* que se convierta en *estructuras de datos* en el repo.

**Comment by JJ** [comment]
> Este ticket discute detalles de implementación relevantes a [HU2] #3

Mencionarse *en el cuerpo del issue*

**Comment by delightfulagony** [comment]
Se ha actualizado el cuerpo del issue para adaptarse al dominio del problema
